### ISSUE TITLE
Замечания по документации с семинара

### ISSUE THREAD

**Issue by nvamelichev** [yutsareva/game-of-life#1]
- Перенести Vision и User Stories в отдельные файлики vision.md, user-stories.md
- Vision: 
    - прописать риски проекта
    - перенести идеи про "задавать правила / начальную конфигурацию / существующие фигуры" в User Stories, это уже уточнение того, что "[Пользователь]... расставляет или генерирует начальную конфигурацию «живых» клеток..."
- Подумать и записать в Vision свои соображения, каких пользователей больше - пассивных наблюдателей (которые хотят посмотреть красивую картинку/рандомную картинку), исследователей игры "Жизнь", ...? 
- Исходя из предположений о пользователях, скорректировать и расширить User Stories (см. предыдущий пункт)

**Comment by nvamelichev** [comment]
@Avonazhrets @yutsareva @safiullinzufar ^^^

**Comment by safiullinzufar** [comment]
fixed
