### ISSUE TITLE
Комментарии по ОО-дизайну

### ISSUE THREAD

**Issue by nvamelichev** [yutsareva/game-of-life#3]
@yutsareva @GSKolesnikov @Avonazhrets @safiullinzufar 

Случайно увидел, что в вашем проекте оказывается есть документ по ОО-дизайну:
https://github.com/yutsareva/game-of-life/blob/main/project-structure.md

Уведомлений об этом мне не приходило :-(
**В следующий раз, пожалуйста, когда всё готово - призывайте меня в комменты (`@nvamelichev`), заведите Issue или Pull Request**. На эти события у меня настроены уведомления, а просто на коммиты в репозитории - нет (слишком шумные были бы уведомления).

----

**В целом, дизайн неплохой, для первой итерации - в особенности** :+1: :+1: :+1:

**Замечания** по [той версии ОО-дизайна, что я увидел](https://github.com/yutsareva/game-of-life/blob/87a15fe38ff60595b28a7e7a77bb7449e9d9bef2/project-structure.md):

- [x] Высокоуровневой дизайн системы в документе перемешан с подробным описанием классов. Пожалуйста, разделите их:
    - [x] Общее описание системы - сделайте в отдельным документом;
    - [x] Описание всех подклассов и их поведения, алгоритма работы Runner - сделайте отдельным документом (если описание будет текстом) или несколькими диаграммами (если описание будет [UML-]диаграммами).
- [x] Класс Cell: 
    - Для высокоуровневого проектирования: класс можно оставить "как есть", потому что концептуально сущность "Клетка" в системе есть.
    - [x] Для уточнённого проектирования: кажется, класс Cell не очень нужен. Судя по текущему набору публичных методов, это просто обёртка над логическим значением (`boolean`): жива клетка или мертва. Класс Cell можно вовсе убрать, а внутри класса Field эффективно представить строки (или столбцы) игрового поля как BitSet'ы (естественно, в публичных методах BitSet не отдавая). В таком случае, ответственность по получению состояния клетки и её изменении перейдёт в класс Field: getCell(), setCell().
- [x] Интерфейс Rules ("правила"), стоит переименовать в Automaton ("автомат") или, точнее, CellularAutomaton ("клеточный автомат"). Название "Rules" подразумевает, что правила - основное, что есть в **публичном** интерфейсе класса, это то, чем он занимается. Но судя по публичному интерфейсу класса Rules - он трансформирует игровое поле и проверяет, можно ли ещё выполнить трансформацию. То есть, для пользователя он выглядит не как "набор правил", а как "клеточный автомат", работающий над прямоугольным игровым полем.
- [x] Интерфейс Reader:
    - [x] Кажется, интерфейс описан слишком подробно. Лучше просто сказать, что у вас в системе есть класс, который умеет прочитать состояние игрового поля и правила откуда-то. Какие конкретно у него будут методы - не очень интересно, это уже детали реализации, отвлекающие от самого интересного - клеточного автомата, игрового поля и т.д.
    - [x] Возможно, недостаёт интерфейса Writer. Подумайте, возможно, логично выглядит функциональность сохранения состояния, чтобы пользователь мог продолжить "с середины", опционально немного изменив настройки? Это, кстати, выглядит как новая вполне валидная User Story для юзера который хочет позалипать над красивыми картинками. Если решите добавить такую функциональность, обновите и ОО-дизайн, и требования к проекту (user-stories.md) :-)
- [x] Очень хочу увидеть более подробное описание **поведения** системы, чем цикл `while` в описании класса `Runner`. Вполне можно (и даже желательно) не кодом, а UML-диаграммой (Sequence / State Machine / Activity).

**Comment by safiullinzufar** [comment]
> Writer

У нас есть Display, который отображает состояния игры в определенный файл с регулируемой частотой, поэтому юзер может потом позалипать в любое состояние.

>  Высокоуровневой дизайн системы в документе перемешан с подробным описанием классов. 

>  Очень хочу увидеть более подробное описание поведения системы

Мы добавим UML.svg файл, из которого всё будет понятно.

**Comment by nvamelichev** [comment]
> У нас есть Display, который отображает состояния игры в определенный файл с регулируемой частотой, поэтому юзер может потом позалипать в любое состояние.

А продолжить симуляцию с любого состояния - пользователь тоже сможет? (Потому что моя идея про Writer - про это как раз). Или вывод Display только для чтения предназначен?

Если Display и выводит состояние симуляции, и сохраняет стейт - возможно, стоит разделить эти две обязанности на два класса (SRP - Single Responsibility Principle)

**Comment by nvamelichev** [comment]
> Мы добавим UML.svg файл, из которого всё будет понятно.

Отлично! Жду от вас диаграммы классов и подробной диаграммы последовательности (более подробной, чем цикл while() в project-structure.md). И лучше бы эти две диаграммы - двумя отдельными файлами

**Comment by safiullinzufar** [comment]
> вывод Display только для чтения предназначен?

Да

**Comment by nvamelichev** [comment]
Ок, давайте прямщас без записи состояния симуляции в файл, т.к. основная аудитория проекта - люди, которые хотят позалипать в красивые картинки :-)

**Comment by yutsareva** [comment]
Добавили [диаграмму последовательности](https://github.com/yutsareva/game-of-life/blob/main/uml-diagrams/sequence.png) и [диаграмму классов](https://github.com/yutsareva/game-of-life/blob/main/uml-diagrams/classes.png).

**Comment by nvamelichev** [comment]
Посмотрел, почти всё хорошо. Поправьте замечания ниже, и первая итерация ОО-дизайна будет принята :-)

1. На диаграмме классов:
    * Нужно показать связи между классами: кто кого использует/вызывает (ассоциация), содержит (агрегация и композиция)
    * Классы-наследники показаны неправильным типом стрелки, правильный - вот такой (в синтаксисе PlantUML): `Суперкласс <|- Подкласс`.

2. Заметил и по project-structure.md и по диаграмме последовательности, что **нет способа прервать симуляцию пока она не завершилась** - если, например, пользователю картинки наскучили. Предлагаю добавить такую возможность - проверять не только `while(!rules.gameFinished(field)) {` :-)

**Comment by yutsareva** [comment]
Поправили

**Comment by nvamelichev** [comment]
Посмотрел обновлённый UML. **Первая итерация дизайна принята, ура!** :+1:

По диаграмме классов пара мелких замечаний осталась:
* Для лучшей читаемости диаграммы, оставьте 1-2 подкласса Command для примера, а остальные уберите - иначе получается "буйство стрелочек"(TM). И посмотрите в сторону layout хинтов PlantUML - стрелочке можно подсказать направление (left/right/up/down), например: `X -left-> Y` - чтобы диаграмма не слишком раздавалась в ширину или в высоту :-)
* Отношения между Runner и {Settings, CellularAutomaton} - скорее агрегация (пустой ромбик), чем композиция (закрашенный ромбик). Ведь настройки и клеточный автомат могут существовать отдельно от запуска симуляции и в ваших юнит-тестах так и будет скорее всего.

**Comment by yutsareva** [comment]
Поправили: https://github.com/yutsareva/game-of-life/blob/main/uml-diagrams/classes.png

**Comment by nvamelichev** [comment]
Отлично! Диаграмма супер, Issue закрываю :-)
